server:
  port: 8080
logging:
  level:
    root: INFO
    com:
      scurtis:
        roster: TRACE
    org:
      hibernate:
        sql: INFO
        type: INFO

spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    database: postgresql
    properties:
      hibernate:
        default_schema: fsu_roster
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/postgres
    username: curtis
    password: curtis
